"""Relationship confidence calculator for criminal network edges."""

from __future__ import annotations

from typing import Dict, Any, List


def calculate_relationship_confidence(
    edge_type: str,
    source_system: str | None = None,
    source_confidence: float | None = None
) -> Dict[str, Any]:
    """Calculate confidence score, description reason, and supporting tags for an edge."""
    
    # Base confidence based on edge type
    score = 80.0
    reason = "Connected through resolved entity mapping."
    supporting_records = ["Case Entity Registry"]
    
    etype = edge_type.lower()
    
    if etype == "owns":
        score = 90.0
        reason = "Officially registered transport registry ownership."
        supporting_records = ["Transport Department Register"]
    elif etype == "registered at":
        score = 85.0
        reason = "Home address match registered with civic authorities."
        supporting_records = ["UIDAI Registry", "Municipal Address Records"]
    elif etype == "called":
        score = 95.0
        reason = "Direct communication CDR records link."
        supporting_records = ["Telecom Call Detail Records (CDR)"]
    elif etype == "detected by cctv":
        score = source_confidence * 100 if source_confidence else 85.0
        reason = "Visual CCTV match flagged by face/license recognition."
        supporting_records = [f"CCTV Footage Record ({source_system or 'City Security'})"]
    elif etype == "linked through similarity":
        score = 75.0
        reason = "Implicit similarity connection generated by multi-model heuristics."
        supporting_records = ["Similar Case Engine Output"]
    elif etype == "linked through timeline":
        score = 80.0
        reason = "Chronological timeline event association."
        supporting_records = ["Unified Dossier Stream"]
    elif etype == "associated with":
        score = 70.0
        reason = "Co-occurrence association flagged in intelligence logs."
        supporting_records = ["Analyst Dossier Notes"]
        
    return {
        "confidence_score": round(score),
        "reason": reason,
        "supporting_records": supporting_records
    }
