"""Router for high-priority operational intelligence alerts."""

from __future__ import annotations

from typing import Any, Dict
from fastapi import APIRouter, Depends

from ..core.security import require_roles
from ..services.analytics.network import alerts_payload

router = APIRouter(prefix="/api", tags=["alerts"])


@router.get("/alerts")
def get_alerts(user: Dict[str, str] = Depends(require_roles("analyst", "supervisor", "admin"))) -> Dict[str, Any]:
    """Retrieve prioritized alerts generated by spatial, network, and risk models."""
    return {"items": alerts_payload(), "human_review_required": True}
